# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.5"
  - "pypy"

env:
  - KOMBU_VERSION=3.0.36

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q kombu==$KOMBU_VERSION
  - pip install -r requirements/test.txt

# command to run tests, e.g. python setup.py test
script: python setup.py nosetests
